# Generated by Django 5.2 on 2025-04-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(blank=True, default='thumbnails/default.webp', null=True, upload_to='thumbnails/'),
        ),
    ]
